--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WavyCraft/Shop
build-by-default: true
branches:
- main
projects:
  Shop:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
    lint: false
...
